name: deploy production
on:
  push:
    branches:
      - 'main'
env:
  SALUT: 'salut'


jobs:
  echo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo ${{secrets.JWT_SECRET}}
      - run: echo ${{env.SALUT}}