name: deploy staging
on:
  push:
    branches:
      - 'staging'
env:
  SALUT: 'salut'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.TEST}}
      - run: echo ${{env.SALUT}}