name: deploy production
on:
  push:
    branches:
      - 'main'
env:
  SALUT: 'salut 213'


jobs:
  echo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo ${{secrets.TEST}}
      - run: echo ${{env.SALUT}}